/**
 * MidnightVault — Membership Contract
 * Auto-generated by compact compile v0.14.0
 * DO NOT EDIT
 */

// Ledger state type representing the public on-chain state
export type Ledger = {
  readonly registeredMembersCount: bigint;
};

// Circuit return type
export type RegisterMemberResult = [];

// Witness function type for private computation
export type MembershipSecretWitness = () => bigint;

// Contract address type
export type ContractAddress = string;

// Deployment state
export type DeployedContract = {
  readonly address: ContractAddress;
  readonly ledger: Ledger;
};

// Circuit descriptor
export const circuits = {
  registerMember: {
    name: 'registerMember',
    k: 17,
    rows: 1024,
    inputs: [{ name: 'expectedSecret', type: 'Field' }],
    outputs: [],
    witnesses: [{ name: 'membershipSecret', type: 'Field' }],
  },
} as const;

// Ledger descriptor
export const ledger = {
  registeredMembersCount: { type: 'Counter', visibility: 'public' },
} as const;

export const contractName = 'Membership';
export const languageVersion = '0.14.0';
