/**
 * MidnightVault — Membership Contract JavaScript Implementation
 * Auto-generated by compact compile v0.14.0
 * DO NOT EDIT
 */

'use strict';

const contractName = 'Membership';
const languageVersion = '0.14.0';

const circuits = {
  registerMember: {
    name: 'registerMember',
    k: 17,
    rows: 1024,
    inputs: [{ name: 'expectedSecret', type: 'Field' }],
    outputs: [],
    witnesses: [{ name: 'membershipSecret', type: 'Field' }],
  },
};

const ledger = {
  registeredMembersCount: { type: 'Counter', visibility: 'public' },
};

module.exports = { contractName, languageVersion, circuits, ledger };
